In [1]:
import mysql.connector
import pandas as pd

1. Antes de empezar a trabajar con la BBDD de Northwind, conozcamos un poco las BBDD que tenemos en nuestro servidor. 
¿Qué BBDD tenemos en nuestro servidor?

In [9]:
mydb = mysql.connector.connect(
              user='root', password='AlumnaAdalab',
              host='127.0.0.1',
              database='information_schema'
)

mycursor = mydb.cursor()

mycursor.execute("SHOW DATABASES")

for i in mycursor:
    print(i)
mycursor.close()
mydb.close()

('bbdd_nba',)
('footfoocker',)
('information_schema',)
('leccion-1-sql',)
('leccion-10-sql',)
('leccion-11-sql',)
('leccion-12-sql',)
('leccion-13-sql',)
('leccion-14-sql',)
('leccion-2-sql',)
('leccion-3-sql',)
('leccion-4-sql',)
('leccion-5-sql',)
('leccion-6-sql',)
('leccion-7-sql',)
('leccion-8-sql',)
('leccion-9-sql',)
('mysql',)
('northwind',)
('performance_schema',)
('project1',)
('proyecto1',)
('pruebas-y-ejercicios',)
('sakila',)
('spotify',)
('sys',)
('tienda',)
('world',)

2. Empezemos a explorar la BBDD de Northwind. ¿Qué tablas componen la BBDD? 
Recuerda que primero nos tendremos que conectar con la BBDD sobre la que queremos trabajar. 
Guarda el resultado de los nombres de la tablas en una lista.

In [10]:
# Volvemos a abrir conexión porque vamos a recoger el nombre de las tablas de otra BBDD, 'northwind'.

mydb = mysql.connector.connect(
              user='root', password='AlumnaAdalab',
              host='127.0.0.1',
              database='northwind'
)

mycursor = mydb.cursor()
mycursor.execute("SHOW TABLES")

lista_tablas = []
for i in mycursor:
    lista_tablas.extend(i)

print(lista_tablas)

mycursor.close()
mydb.close()

['categories', 'customer_customer_demo', 'customer_demographics', 'customers', 'employee_territories', 'employees', 'order_details', 'orders', 'products', 'region', 'shippers', 'suppliers', 'territories']

3. ¿Qué columnas tiene cada una de las tablas? Para esto tendréis que hacer un for loop para que nos saque el resultado de todas las columnas.

In [13]:
# Volvemos a abrir conexión porque vamos a recoger el nombre de las columnas de cada tabla de northwind desde otra BBDD, 'information_schema'.

mydb = mysql.connector.connect(
              user='root', password='AlumnaAdalab',
              host='127.0.0.1',
              database='information_schema'
)

mycursor = mydb.cursor()

query_columnas = "SELECT TABLE_NAME, COLUMN_NAME FROM COLUMNS WHERE TABLE_SCHEMA = 'northwind'"

mycursor.execute(query_columnas)

for x in mycursor:
    print(x)

mycursor.close()
mydb.close()

('categories', 'category_id')
('categories', 'category_name')
('categories', 'description')
('categories', 'picture')
('customer_customer_demo', 'customer_id')
('customer_customer_demo', 'customertype_id')
('customer_demographics', 'customer_desc')
('customer_demographics', 'customer_type_id')
('customers', 'address')
('customers', 'city')
('customers', 'company_name')
('customers', 'contact_name')
('customers', 'contact_title')
('customers', 'country')
('customers', 'customer_id')
('customers', 'fax')
('customers', 'phone')
('customers', 'postal_code')
('customers', 'region')
('employee_territories', 'employee_id')
('employee_territories', 'territory_id')
('employees', 'address')
('employees', 'birth_date')
('employees', 'city')
('employees', 'country')
('employees', 'employee_id')
('employees', 'extension')
('employees', 'first_name')
('employees', 'hire_date')
('employees', 'home_phone')
('employees', 'last_name')
('employees', 'notes')
('employees', 'photo')
('employees', 'photo_path')
('employees', 'postal_code')
('employees', 'region')
('employees', 'reports_to')
('employees', 'title')
('employees', 'title_of_courtesy')
('order_details', 'discount')
('order_details', 'order_id')
('order_details', 'product_id')
('order_details', 'quantity')
('order_details', 'unit_price')
('orders', 'customer_id')
('orders', 'employee_id')
('orders', 'freight')
('orders', 'order_date')
('orders', 'order_id')
('orders', 'required_date')
('orders', 'ship_address')
('orders', 'ship_city')
('orders', 'ship_country')
('orders', 'ship_name')
('orders', 'ship_postal_code')
('orders', 'ship_region')
('orders', 'ship_via')
('orders', 'shipped_date')
('products', 'category_id')
('products', 'discontinued')
('products', 'product_id')
('products', 'product_name')
('products', 'quantity_per_unit')
('products', 'reorder_level')
('products', 'supplier_id')
('products', 'unit_price')
('products', 'units_in_stock')
('products', 'units_on_order')
('region', 'region_description')
('region', 'region_id')
('shippers', 'company_name')
('shippers', 'phone')
('shippers', 'shipper_id')
('suppliers', 'adress')
('suppliers', 'city')
('suppliers', 'company_name')
('suppliers', 'contact_name')
('suppliers', 'contact_title')
('suppliers', 'country')
('suppliers', 'fax')
('suppliers', 'home_page')
('suppliers', 'phone')
('suppliers', 'postal_code')
('suppliers', 'region')
('suppliers', 'supplier_id')
('territories', 'region_id')
('territories', 'territory_description')
('territories', 'territory_id')

4. Hagamos unas queries facilitas:
- Extraed el primer pedido donde se ha gastado más. Devolved el id del pedido y la cantidad gastada.
- Devuelve la misma query que en el anterior ejercicio, pero en este caso devuelve todos los resultados.
- Extraed el números de pedidos que se hayan hecho por dia. Devuelve los resultados en una dataframe.
- Extraer los pedidos hechos por "Nancy Daviolo". Tendréis que hacer una subquery.

In [19]:
# Extraed el primer pedido donde se ha gastado más. Devolved el id del pedido y la cantidad gastada.

mydb = mysql.connector.connect(
              user='root', password='AlumnaAdalab',
              host='127.0.0.1',
              database='northwind'
)

mycursor = mydb.cursor()

mycursor.execute("SELECT order_id, MAX(unit_price * quantity) AS Cantidad_gastada FROM order_details GROUP BY order_id ORDER BY Cantidad_gastada DESC LIMIT 1")

for y in mycursor:
    print (y)

(10865, 15810.0)

In [20]:
# Devuelve la misma query que en el anterior ejercicio, pero en este caso devuelve todos los resultados.

mycursor.execute("SELECT order_id, MAX(unit_price * quantity) AS Cantidad_gastada FROM order_details GROUP BY order_id ORDER BY Cantidad_gastada DESC")

for y in mycursor:
    print (y)

(10865, 15810.0)
(10981, 15810.0)
(10353, 10540.0)
(10417, 10540.0)
(10889, 10540.0)
(10424, 10329.2)
(10897, 9903.2)
(10372, 8432.0)
(10540, 7905.0)
(10816, 7905.0)
(10817, 7905.0)
(10912, 7427.400000000001)
(11030, 7427.400000000001)
(11032, 6587.5)
(10776, 6360.0)
(10479, 6324.0)
(10993, 6189.5)
(11017, 6050.0)
(10515, 5268.0)
(10691, 4951.6)
(10687, 4850.0)
(10510, 4456.4400000000005)
(10666, 4456.4400000000005)
(11072, 4322.5)
(10329, 4216.0)
(10351, 4216.0)
(10953, 4050.0)
(10518, 3952.5)
(10616, 3952.5)
(10672, 3952.5)
(10633, 3944.0)
(10711, 3935.9999999999995)
(10607, 3900.0)
(10678, 3800.0)
(10360, 3465.0)
(10595, 3420.0)
(10895, 3400.0)
(11008, 3192.0)
(10514, 3159.0)
(10634, 3125.0)
(10854, 3100.0)
(10267, 3080.0)
(10430, 3080.0)
(11064, 3003.0)
(10893, 2970.96)
(10949, 2958.0)
(10324, 2808.0)
(10524, 2760.0)
(10316, 2758.0)
(10841, 2750.0)
(10688, 2736.0)
(10694, 2700.0)
(10561, 2650.0)
(10490, 2640.0)
(10805, 2635.0)
(10252, 2592.0)
(10549, 2544.0)
(10588, 2500.0)
(10629, 2475.8)
(10787, 2475.8)
(10801, 2475.8)
(10305, 2475.0)
(10745, 2475.0)
(10852, 2465.0)
(10605, 2380.0)
(10440, 2376.0)
(10764, 2340.0)
(11021, 2332.0)
(10701, 2310.0)
(10851, 2310.0)
(10398, 2304.0)
(10451, 2304.0)
(11033, 2296.0)
(10402, 2281.5)
(10570, 2280.0)
(10637, 2280.0)
(10762, 2280.0)
(10344, 2240.0)
(10345, 2240.0)
(10772, 2228.2200000000003)
(10567, 2200.0)
(10823, 2200.0)
(10892, 2200.0)
(10598, 2195.0)
(11053, 2187.5)
(10339, 2184.0)
(10359, 2176.0)
(10612, 2170.0)
(10886, 2170.0)
(10401, 2128.0)
(10948, 2120.0)
(10831, 2108.0)
(10638, 2088.0)
(10400, 2079.0)
(10836, 2040.0)
(10335, 2035.1999999999998)
(10332, 2000.0)
(10369, 1980.0)
(10546, 1972.0)
(10988, 1972.0)
(10601, 1925.0)
(10703, 1925.0)
(10990, 1881.0)
(10789, 1875.0)
(10658, 1870.0)
(10395, 1834.0)
(10384, 1814.3999999999999)
(10894, 1800.0)
(10987, 1800.0)
(11001, 1800.0)
(10465, 1782.0)
(10760, 1756.0)
(10921, 1756.0)
(10441, 1755.0)
(10618, 1750.0)
(10393, 1743.0)
(10941, 1739.9999999999998)
(10791, 1733.0600000000002)
(10971, 1733.0600000000002)
(10904, 1725.5)
(10657, 1710.0)
(10593, 1701.0)
(10660, 1701.0)
(10742, 1700.0)
(11056, 1700.0)
(10249, 1696.0)
(10765, 1684.0)
(10938, 1666.0)
(11068, 1656.0)
(10617, 1650.0)
(11036, 1650.0)
(10861, 1638.0)
(10419, 1632.0)
(10503, 1627.5)
(10667, 1620.0)
(10878, 1620.0)
(10991, 1620.0)
(10513, 1600.0)
(10709, 1600.0)
(10997, 1600.0)
(10845, 1596.0)
(10731, 1590.0)
(10802, 1590.0)
(10457, 1584.0)
(10286, 1576.0)
(10413, 1576.0)
(10516, 1562.5)
(10838, 1562.5)
(10877, 1562.5)
(10431, 1560.0)
(10530, 1560.0)
(10847, 1560.0)
(10420, 1552.0)
(10452, 1550.0)
(10979, 1536.5)
(10406, 1528.8)
(10519, 1520.0)
(10555, 1520.0)
(10470, 1500.0)
(10511, 1500.0)
(10361, 1496.0)
(10698, 1485.48)
(10290, 1485.0)
(10250, 1484.0)
(10757, 1479.0)
(10340, 1472.0)
(10392, 1440.0)
(10746, 1440.0)
(10812, 1392.0)
(10382, 1386.0)
(11023, 1380.0)
(11052, 1380.0)
(10408, 1379.0)
(10449, 1379.0)
(10750, 1375.0)
(10799, 1375.0)
(10718, 1368.0)
(10924, 1368.0)
(10795, 1365.0)
(10962, 1350.0)
(10343, 1330.0)
(10255, 1320.0)
(10298, 1320.0)
(10488, 1320.0)
(11028, 1320.0)
(10783, 1317.5)
(10964, 1317.5)
(11041, 1317.0)
(10756, 1312.5)
(10455, 1310.0)
(10292, 1296.0)
(10700, 1290.0)
(11012, 1290.0)
(10773, 1287.0)
(11045, 1272.0)
(10645, 1250.0)
(10871, 1250.0)
(10302, 1248.0)
(10330, 1245.0)
(10263, 1242.0)
(10583, 1237.9)
(10857, 1237.9)
(11007, 1237.9)
(10429, 1228.5)
(10436, 1216.0)
(10523, 1215.0)
(10986, 1215.0)
(10786, 1200.0)
(11039, 1200.0)
(10536, 1190.0)
(11059, 1190.0)
(10686, 1170.0)
(10796, 1163.75)
(10461, 1152.0)
(10526, 1140.0)
(10543, 1140.0)
(10547, 1140.0)
(10712, 1140.0)
(10755, 1140.0)
(10820, 1140.0)
(10968, 1140.0)
(10566, 1125.0)
(10346, 1123.2)
(10985, 1120.0)
(10804, 1116.0)
(10325, 1112.0)
(10459, 1112.0)
(10258, 1105.0)
(10641, 1104.0)
(10706, 1104.0)
(10527, 1100.0)
(10533, 1100.0)
(10930, 1097.5)
(10458, 1092.0)
(10481, 1088.0)
(10693, 1080.0)
(10747, 1080.0)
(10918, 1080.0)
(10961, 1080.0)
(11022, 1080.0)
(11035, 1080.0)
(11024, 1075.0)
(10608, 1064.0)
(10748, 1064.0)
(10486, 1060.0)
(10558, 1060.0)
(10663, 1060.0)
(10665, 1060.0)
(10995, 1060.0)
(11055, 1060.0)
(10541, 1054.0)
(10596, 1053.6)
(10714, 1053.0)
(10535, 1050.0)
(10766, 1050.0)
(10800, 1050.0)
(10388, 1048.0)
(10713, 1045.0)
(10575, 1044.0)
(10784, 1044.0)
(10866, 1035.6)
(11027, 1035.3)
(10396, 1032.0)
(10314, 1024.0)
(10684, 1020.0)
(10830, 1020.0)
(10603, 1008.0)
(10989, 1000.0)
(10557, 997.5)
(10859, 997.5)
(10834, 990.32)
(10268, 990.0)
(10994, 990.0)
(10554, 986.0)
(10779, 986.0)
(10872, 986.0)
(10721, 972.5)
(10522, 960.0)
(11002, 960.0)
(10984, 959.75)
(10283, 952.0)
(10285, 943.1999999999999)
(10677, 936.9)
(10265, 936.0)
(10368, 931.0)
(10681, 931.0)
(10644, 920.0)
(10814, 920.0)
(10270, 919.9999999999999)
(10572, 919.9999999999999)
(10744, 919.9999999999999)
(10418, 912.0)
(10464, 912.0)
(10494, 912.0)
(10499, 912.0)
(10649, 912.0)
(10733, 912.0)
(10855, 912.0)
(10976, 912.0)
(10717, 900.0)
(10729, 900.0)
(10808, 900.0)
(11050, 900.0)
(10312, 883.1999999999999)
(10273, 882.0)
(10423, 880.0)
(10692, 878.0)
(10977, 878.0)
(10257, 877.5)
(10680, 872.5)
(10297, 864.0)
(10364, 864.0)
(10373, 860.0)
(10880, 855.0)
(10933, 855.0)
(10433, 851.1999999999999)
(10774, 850.0)
(10362, 848.0)
(10965, 848.0)
(10736, 842.0)
(10327, 840.0)
(10619, 840.0)
(10635, 840.0)
(10868, 840.0)
(10556, 835.1999999999999)
(10803, 825.0)
(10835, 825.0)
(10573, 819.9999999999999)
(10650, 819.9999999999999)
(10442, 816.0)
(10475, 816.0)
(10954, 816.0)
(11031, 810.0)
(10829, 800.0)
(10967, 800.0)
(10978, 800.0)
(10370, 798.0)
(10884, 798.0)
(10999, 795.0)
(10389, 788.0)
(10260, 780.0)
(10590, 780.0)
(10696, 780.0)
(10707, 780.0)
(10727, 780.0)
(10551, 778.0)
(10751, 776.7)
(10957, 776.7)
(10946, 775.0)
(10342, 768.0)
(10397, 763.1999999999999)
(10472, 763.1999999999999)
(10690, 760.0)
(10781, 760.0)
(10790, 760.0)
(11018, 760.0)
(11029, 760.0)
(11046, 760.0)
(10670, 750.0)
(10719, 750.0)
(10734, 750.0)
(10404, 747.0)
(10421, 747.0)
(10487, 747.0)
(10357, 744.0)
(10664, 744.0)
(11020, 744.0)
(10624, 742.74)
(10560, 739.5)
(10627, 739.5)
(10769, 739.5)
(10309, 736.0)
(11063, 736.0)
(10844, 735.0)
(10537, 730.8)
(10277, 728.0)
(10377, 728.0)
(10347, 720.0)
(10471, 720.0)
(10485, 720.0)
(10640, 720.0)
(10869, 720.0)
(10902, 720.0)
(11070, 720.0)
(10403, 714.0)
(11058, 714.0)
(10504, 712.5)
(10410, 704.0)
(10675, 697.5)
(10337, 695.0)
(10497, 695.0)
(10932, 690.1999999999999)
(10507, 690.0)
(10333, 688.0)
(10643, 684.0)
(10944, 684.0)
(10626, 680.0)
(10653, 680.0)
(10328, 672.0)
(10492, 672.0)
(10272, 667.2)
(10390, 667.2)
(10876, 665.0)
(10278, 660.0)
(10679, 660.0)
(10913, 660.0)
(10825, 656.0)
(10474, 655.1999999999999)
(10427, 651.0)
(10715, 651.0)
(10661, 649.25)
(10552, 648.0)
(10646, 645.0)
(10901, 645.0)
(11038, 645.0)
(10848, 640.5)
(11047, 640.5)
(10253, 640.0)
(10818, 640.0)
(10975, 640.0)
(10580, 631.5)
(10630, 630.0)
(10689, 630.0)
(10740, 630.0)
(10584, 625.0)
(10722, 625.0)
(10768, 625.0)
(10853, 625.0)
(10758, 624.6)
(10338, 624.0)
(10564, 624.0)
(10411, 620.0)
(10685, 620.0)
(10301, 608.0)
(10383, 608.0)
(10469, 608.0)
(10896, 608.0)
(10293, 600.0)
(10399, 600.0)
(10659, 600.0)
(10833, 600.0)
(10908, 600.0)
(10929, 600.0)
(10982, 600.0)
(11010, 600.0)
(10565, 598.5)
(10966, 591.5999999999999)
(11044, 591.5999999999999)
(10303, 588.0)
(10447, 588.0)
(10890, 585.0)
(10922, 585.0)
(10931, 585.0)
(10356, 576.0)
(10294, 571.1999999999999)
(10525, 570.0)
(10632, 570.0)
(10642, 570.0)
(10669, 570.0)
(10735, 570.0)
(10749, 570.0)
(10936, 570.0)
(10849, 562.14)
(10379, 561.6)
(10463, 560.0)
(10939, 560.0)
(10942, 560.0)
(10996, 560.0)
(10269, 556.0)
(10287, 556.0)
(10468, 552.0)
(10811, 552.0)
(10636, 550.0)
(10726, 550.0)
(11000, 550.0)
(11005, 550.0)
(10656, 544.6)
(10284, 544.0)
(10385, 544.0)
(10569, 540.0)
(10623, 540.0)
(10914, 537.5)
(10264, 532.0)
(11011, 530.0)
(11026, 530.0)
(10387, 528.0)
(10480, 528.0)
(10828, 527.0)
(10780, 525.0)
(10862, 525.0)
(11048, 525.0)
(10380, 524.0)
(10839, 522.0)
(10350, 518.4)
(10320, 516.0)
(10611, 510.0)
(10728, 510.0)
(11061, 510.0)
(10319, 509.59999999999997)
(10407, 504.0)
(10553, 504.0)
(10983, 504.0)
(10639, 500.0)
(10934, 500.0)
(11076, 500.0)
(10668, 498.75)
(10450, 496.0)
(10478, 496.0)
(10724, 496.0)
(10562, 493.0)
(10574, 493.0)
(10599, 493.0)
(10606, 493.0)
(10671, 493.0)
(10563, 490.0)
(10761, 490.0)
(11066, 490.0)
(10304, 480.0)
(10925, 475.0)
(10723, 468.45)
(10279, 468.0)
(10911, 468.0)
(10827, 465.0)
(10846, 462.0)
(10923, 460.0)
(10788, 459.99999999999994)
(10837, 459.99999999999994)
(10439, 456.0)
(11077, 456.0)
(10600, 450.0)
(10628, 450.0)
(10697, 450.0)
(10850, 450.0)
(10885, 450.0)
(11071, 450.0)
(10903, 442.05)
(10943, 441.0)
(10858, 439.0)
(10974, 439.0)
(10826, 437.5)
(10443, 436.79999999999995)
(10296, 432.0)
(10559, 432.0)
(10906, 427.5)
(10958, 427.0)
(10956, 424.0)
(10326, 422.40000000000003)
(10376, 420.0)
(10498, 420.0)
(10502, 420.0)
(10651, 420.0)
(10797, 420.0)
(10813, 420.0)
(10919, 418.79999999999995)
(10576, 408.45)
(10676, 408.45)
(10300, 408.0)
(10512, 408.0)
(10532, 408.0)
(10927, 405.0)
(10365, 403.20000000000005)
(10254, 403.2)
(10367, 403.2)
(10405, 400.0)
(10695, 400.0)
(10763, 400.0)
(10882, 400.0)
(10952, 400.0)
(10610, 399.0)
(10594, 397.5)
(10341, 396.0)
(10354, 396.0)
(10307, 394.0)
(10394, 394.0)
(10256, 393.0)
(10437, 393.0)
(10483, 392.0)
(10571, 392.0)
(10355, 390.0)
(10597, 390.0)
(10915, 390.0)
(10916, 390.0)
(10920, 390.0)
(10891, 388.35)
(11015, 388.35)
(10581, 387.5)
(10592, 387.5)
(10951, 387.5)
(10280, 384.0)
(10622, 380.0)
(10806, 380.0)
(10856, 380.0)
(10888, 380.0)
(10720, 378.0)
(10935, 378.0)
(10444, 373.5)
(10591, 372.5)
(10276, 372.0)
(10291, 372.0)
(10412, 372.0)
(10716, 371.0)
(10500, 364.8)
(10937, 364.8)
(10266, 364.79999999999995)
(10262, 360.0)
(10315, 360.0)
(10529, 360.0)
(10578, 360.0)
(10587, 360.0)
(10647, 360.0)
(10654, 360.0)
(10732, 360.0)
(10821, 360.0)
(10860, 360.0)
(10863, 360.0)
(10905, 360.0)
(10909, 360.0)
(11069, 360.0)
(11075, 360.0)
(10794, 348.75)
(10798, 348.0)
(10926, 348.0)
(10274, 344.0)
(10771, 344.0)
(11009, 342.0)
(10625, 340.0)
(10917, 340.0)
(10251, 336.0)
(10456, 336.0)
(10743, 336.0)
(11062, 328.0)
(10621, 322.5)
(10819, 322.0)
(10759, 320.0)
(10544, 319.2)
(10336, 316.8)
(10542, 315.0)
(10648, 315.0)
(10770, 315.0)
(10842, 315.0)
(10528, 313.2)
(10416, 312.0)
(10550, 312.0)
(10832, 311.2)
(10609, 310.0)
(10613, 310.0)
(10785, 310.0)
(10874, 310.0)
(10980, 310.0)
(10704, 306.0)
(10358, 304.0)
(11016, 304.0)
(10374, 300.0)
(10453, 300.0)
(10875, 300.0)
(10448, 294.0)
(10614, 294.0)
(11042, 291.75)
(10261, 288.0)
(10317, 288.0)
(10425, 288.0)
(10477, 288.0)
(10493, 288.0)
(10741, 285.0)
(10652, 280.0)
(10777, 280.0)
(10970, 280.0)
(11054, 280.0)
(10375, 279.0)
(10435, 278.0)
(10454, 278.0)
(10673, 276.0)
(11014, 270.2)
(10702, 270.0)
(10275, 264.0)
(10306, 262.0)
(10730, 261.75)
(10434, 259.2)
(10534, 258.9)
(10489, 252.0)
(10506, 252.0)
(10582, 252.0)
(10705, 250.0)
(10432, 249.0)
(11006, 247.58)
(11074, 244.29999999999998)
(10289, 240.0)
(10299, 240.0)
(10940, 240.0)
(10438, 234.0)
(10577, 234.0)
(10972, 234.0)
(11034, 233.39999999999998)
(10491, 232.5)
(10682, 232.5)
(10998, 232.5)
(10960, 231.60000000000002)
(10409, 223.20000000000002)
(10879, 220.79999999999998)
(10517, 220.0)
(10947, 220.0)
(10348, 216.0)
(10843, 212.0)
(10460, 210.0)
(10545, 210.0)
(10864, 210.0)
(11043, 210.0)
(11073, 210.0)
(10473, 206.39999999999998)
(10311, 201.6)
(10363, 200.0)
(10496, 200.0)
(10873, 200.0)
(10910, 200.0)
(11040, 200.0)
(10310, 197.0)
(10655, 193.0)
(10428, 192.0)
(10792, 190.0)
(11013, 190.0)
(11049, 190.0)
(11004, 187.38)
(10426, 186.20000000000002)
(10775, 186.0)
(11003, 184.0)
(10313, 182.39999999999998)
(10508, 180.0)
(10604, 180.0)
(10840, 180.0)
(11025, 180.0)
(10248, 174.0)
(10466, 168.0)
(10520, 164.0)
(10579, 162.75)
(10973, 156.15)
(10568, 155.0)
(10959, 155.0)
(10318, 154.0)
(10495, 154.0)
(10462, 151.20000000000002)
(10539, 150.0)
(10881, 150.0)
(10501, 149.0)
(11065, 149.0)
(10505, 147.89999999999998)
(10822, 147.89999999999998)
(10482, 147.0)
(10484, 147.0)
(10321, 144.0)
(10476, 144.0)
(10725, 144.0)
(10752, 144.0)
(10899, 144.0)
(10585, 142.5)
(10349, 141.60000000000002)
(10548, 140.0)
(10809, 140.0)
(10509, 136.8)
(11060, 136.0)
(10793, 135.1)
(10824, 135.0)
(10467, 134.39999999999998)
(10414, 131.4)
(10739, 126.0)
(10662, 125.0)
(10945, 125.0)
(10282, 124.19999999999999)
(10295, 121.6)
(10615, 120.0)
(10352, 118.0)
(10737, 115.80000000000001)
(10699, 114.0)
(10322, 112.0)
(10381, 112.0)
(10386, 112.0)
(10531, 110.0)
(10950, 110.0)
(10907, 108.5)
(10969, 108.0)
(10870, 106.0)
(10538, 105.0)
(10378, 103.19999999999999)
(10334, 100.0)
(10867, 98.39999999999999)
(10521, 96.5)
(10778, 96.5)
(10708, 95.0)
(10955, 93.0)
(10371, 91.19999999999999)
(10928, 90.0)
(10331, 88.5)
(10445, 88.5)
(10446, 87.6)
(11067, 86.85000000000001)
(10391, 86.39999999999999)
(10366, 84.0)
(10259, 80.0)
(10810, 75.0)
(10589, 72.0)
(10887, 70.0)
(10992, 69.6)
(10963, 68.0)
(10602, 65.0)
(10683, 63.0)
(10415, 62.4)
(10323, 62.0)
(10631, 62.0)
(10308, 60.0)
(11037, 60.0)
(10288, 59.0)
(10281, 57.6)
(10754, 55.199999999999996)
(10738, 52.349999999999994)
(10753, 50.0)
(10422, 49.8)
(10271, 48.0)
(10710, 47.5)
(10674, 45.0)
(10900, 45.0)
(11051, 45.0)
(11057, 45.0)
(10815, 40.0)
(11019, 40.0)
(10883, 36.0)
(10620, 35.0)
(10898, 30.0)
(10586, 28.0)
(10767, 28.0)
(10807, 18.4)
(10782, 12.5)

In [21]:
# Extraed el números de pedidos que se hayan hecho por dia. Devuelve los resultados en una dataframe.

mycursor.execute("SELECT COUNT(order_id), order_date FROM orders GROUP BY order_date")

pd.DataFrame (mycursor, columns= ['Número de pedidos', 'Día']) # El dataframe nos permite sacar los resultados en una tabla de 2 dimensiones

     Número de pedidos        Día
0                    1 1996-07-04
1                    1 1996-07-05
2                    2 1996-07-08
3                    1 1996-07-09
4                    1 1996-07-10
..                 ...        ...
475                  4 1998-04-30
476                  3 1998-05-01
477                  3 1998-05-04
478                  4 1998-05-05
479                  4 1998-05-06

[480 rows x 2 columns]

In [22]:
# Extraer los pedidos hechos por "Nancy Davolio**". Tendréis que hacer una subquery.
# ** Ojo, estaba mal escrito en el enunciado

query_nd = "SELECT order_id, employee_id AS 'Nancy Davolio ID' FROM orders WHERE employee_id IN (SELECT employee_id FROM employees WHERE first_name = 'Nancy' AND last_name = 'Davolio')"
mycursor.execute(query_nd)

for q in mycursor:
    print (q)

(10258, 1)
(10270, 1)
(10275, 1)
(10285, 1)
(10292, 1)
(10293, 1)
(10304, 1)
(10306, 1)
(10311, 1)
(10314, 1)
(10316, 1)
(10325, 1)
(10340, 1)
(10351, 1)
(10357, 1)
(10361, 1)
(10364, 1)
(10371, 1)
(10374, 1)
(10376, 1)
(10377, 1)
(10385, 1)
(10387, 1)
(10393, 1)
(10394, 1)
(10396, 1)
(10400, 1)
(10401, 1)
(10405, 1)
(10453, 1)
(10461, 1)
(10465, 1)
(10469, 1)
(10473, 1)
(10482, 1)
(10486, 1)
(10508, 1)
(10524, 1)
(10525, 1)
(10537, 1)
(10542, 1)
(10546, 1)
(10558, 1)
(10562, 1)
(10567, 1)
(10579, 1)
(10587, 1)
(10591, 1)
(10598, 1)
(10604, 1)
(10605, 1)
(10612, 1)
(10616, 1)
(10618, 1)
(10626, 1)
(10630, 1)
(10653, 1)
(10655, 1)
(10664, 1)
(10665, 1)
(10668, 1)
(10671, 1)
(10677, 1)
(10680, 1)
(10689, 1)
(10690, 1)
(10709, 1)
(10710, 1)
(10713, 1)
(10717, 1)
(10718, 1)
(10733, 1)
(10743, 1)
(10746, 1)
(10773, 1)
(10776, 1)
(10785, 1)
(10788, 1)
(10789, 1)
(10792, 1)
(10800, 1)
(10813, 1)
(10821, 1)
(10825, 1)
(10827, 1)
(10834, 1)
(10835, 1)
(10842, 1)
(10850, 1)
(10859, 1)
(10877, 1)
(10886, 1)
(10888, 1)
(10894, 1)
(10900, 1)
(10902, 1)
(10909, 1)
(10910, 1)
(10916, 1)
(10921, 1)
(10928, 1)
(10946, 1)
(10950, 1)
(10952, 1)
(10968, 1)
(10969, 1)
(10975, 1)
(10976, 1)
(10981, 1)
(10984, 1)
(10991, 1)
(10992, 1)
(10995, 1)
(11012, 1)
(11023, 1)
(11027, 1)
(11038, 1)
(11039, 1)
(11064, 1)
(11067, 1)
(11069, 1)
(11071, 1)
(11077, 1)

5. Para finalizar el ejercicio, desconectad la conexión con el servidor.

In [23]:
mycursor.close()
mydb.close()